version: '3'
services:
  app:
    image: app
    build:
      context: app/SalesManagement
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd!
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql/data
  dev:
    image: dev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    working_dir: /root/workspace
    build: .
    volumes:
      - .:/root/workspace
    depends_on:
      - db
volumes:
  mssql-data:
    driver: local