app_frontend: npm run app:frontend
app_backend: npm run app:backend
app_api: npm run sam:local
app_webpack: npm run app:webpack
watch_frontend: npm run watch:frontend
watch_backend: npm run watch:backend
