AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - org.hiroshima_arc::fizzbuzz

Parameters:
  ApiUrl:
    Type: String
    Description: Default api url
    Default: 'https://api.hiroshima-arc.org'

Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  FizzbuzzFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: org.hiroshima_arc.StreamLambdaHandler::handleRequest
      Runtime: java8
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: production
          API_URL: !Ref ApiUrl
      CodeUri: target/fizzbuzz-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  FizzbuzzApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/fizzbuzz'
    Export:
      Name: FizzbuzzApi
