# frozen_string_literal: true

source 'https://rubygems.org'

gem 'json'
gem 'rack'
gem 'rack-contrib'
gem 'rake'
gem 'rubysl-base64'
gem 'sinatra'

group :development do
  gem 'rubocop', require: false
  gem 'shotgun'
end

group :test do
  gem 'mocha'
  gem 'rack-test'
  gem 'rspec'
  gem 'test-unit'
end
