AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  api

  Sample SAM Template for api

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  Stage:
    Type: String
    Description: Application deployment stage
    Default: ''
  ApiUrl:
    Type: String
    Description: Default api url
    Default: 'https://api.hiroshima-arc.org'

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs10.x
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
  ExpressFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: ExpressApp
      Handler: lambda.handler
      Runtime: nodejs10.x
      Environment:
        Variables:
          NODE_ENV: production
          API_URL: !Ref ApiUrl
      Policies:
        - AmazonDynamoDBFullAccess
      CodeUri: src/
      MemorySize: 512
      Timeout: 30
      Events:
        ExpressApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId: !Ref ExpressAPI
  ExpressAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: ExpressAPI
      StageName: Prod
      DefinitionBody:
        swagger: '2.0'
        basePath: '/Prod'
        info:
          title: !Ref AWS::StackName
        paths:
          /{proxy+}:
            x-amazon-apigateway-any-method:
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ExpressFunction.Arn}/invocations'
                passthroughBehavior: "when_no_match"
                httpMethod: POST
                type: "aws_proxy"
          /:
            get:
              responses: {}
              x-amazon-apigateway-integration:
                uri:
                  !Sub 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ExpressFunction.Arn}/invocations'
                passthroughBehavior: "when_no_match"
                httpMethod: POST
                type: "aws_proxy"
  ConfigLambdaPermission:
    Type: "AWS::Lambda::Permission"
    DependsOn:
      - ExpressFunction
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref ExpressFunction
      Principal: apigateway.amazonaws.com

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  ExpressAppUrl:
    Description: App endpoint URL
    Value: !Sub "https://${ExpressAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
