:toc: left
:toclevels: 5
:sectnums:

= 見知らぬ、構造化プログラミング

== 概要
=== 実施日時
* https://hiroshima-arc.connpass.com/event/109589/[2018年11月16日（金） 18:00 - 21:00]

=== 会場

++++
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d6584.583947396631!2d132.458662!3d34.393924!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xe874ed70577dcf46!2z44Kz44Ov44O844Kt44Oz44Kw44K544Oa44O844K5IFNoYWtlSGFuZHM!5e0!3m2!1sja!2sjp!4v1541923570346" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
++++

=== 参加メンバー
* https://portfolio.forkwell.com/@k2works[テストおじさん]
* リモートさん
* テスト鬼さん
* テスト初めて書いたひと

=== お題
* http://www.hiroshima-arc.org/re_zero_tdd/fizz_buzz.html[FizzBuzz]
* FizzBuzz をクラスを使わずにテスト駆動で実装する。

=== 言語
* Python 3.6

== セッション

=== 前回までのあらすじ

http://www.hiroshima-arc.org/re_zero_tdd/session/20181109.html#_problem[前回のセッション]でクラスベースだとオブジェクト指向に関する解説も必要になることがわかったテストおじさん。

そこで今回はクラスを使わずにテスト駆動開発をやってみることにしたのであった。

さてさてどうなることやら・・・

=== TODOリストから始めるアジャイルソフトウェア開発

==== 仕様

*テストおじさん*: はい、第２回 Re:ゼロから始めるテスト駆動開発 はじめます、レポジトリは https://github.com/hiroshima-arc/re_zero_tdd[ここ]ね。

*リモートさん*: 今日は家からうっすら参加です。ご飯を食べたりで適当に抜けています。

*テスト鬼さん*: よろしくお願いします。

*テスト初めて書いたひと*: よろしくお願いします。

*テストおじさん*: 今日はFizzBuzzをクラスを使わずにテスト駆動で実装してみたいと思います。

*テストおじさん*: 今回のお題の仕様です。

> 1 から 100 までの数をプリントするプログラムを書け。
> ただし 3 の倍数のときは数の代わりに｢Fizz｣と、5 の倍数のときは｢Buzz｣とプリントし、3 と 5 両方の倍数の場合には｢FizzBuzz｣とプリントすること。

*テストおじさん*: http://www.hiroshima-arc.org/re_zero_tdd/session/20181109.html#_%E3%82%BB%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3[前回のセッション]との違いとして今回はコンソールに出力させるというのが大きな違いですかね。

==== TODOリスト

*テストおじさん*: 最初にまず [red]#TODOリスト# の作成をしましょう。

[quote, 'https://amzn.to/2QtCA5b[テスト駆動開発]']
____
TODOリスト

何をテストすべきだろうか----着手する前に、必要になりそうなテストをリストに書き出しておこう。
____

*テストおじさん*: 仕様からTODOリストを作成するわけですがここは [red]#一つのプログラムには一つのことをうまくやらせる# の原則に従ってシンプルにやってみましょう。

TODOリストを書き出すテストおじさん。

* [ ] 1 から 100 まで数をプリントできるようにする。
* [ ] 3 の倍数のときは数の代わりに｢Fizz｣をプリントできるようにする。
* [ ] 5 の倍数のときは｢Buzz｣とプリントできるようにする。
* [ ] 3 と 5 両方の倍数の場合には｢FizzBuzz｣とプリントできるようにする。

*テストおじさん*: まずは100回繰り返し処理をすることをどうやって実装するかを考えるとして条件に関しては一旦置いておきましょう。

*テストおじさん*: 一つのTODOには一つのことをテストできるようにする・・・みたいな。

==== アジャイルソフトウェア開発

*テスト鬼さん*: TODOリストの粒度はどれくらいが適切なんですかね？

*テストおじさん*: 自分はテストメソッドに対応するぐらいを目安に書いてますね。

*テスト初めて書いたひと*: 実際の開発だとTODOリストの粒度って立場によって変わってくると思うんですがどう取りまとめて行けばいいんですかね？

*テストおじさん*: そうですよね、作業者レベルのTODOもアプリケーションの要求から落とし込まないといけませよね。

*テストおじさん*: そういったものをどう取り扱うかは [red]#アジャイルソフトウェア開発手法# が参考になるかと思います。

*テスト初めて書いたひと*: アジャイル?

*テストおじさん*: えーとです、例えば今日のお題の仕様ですが。

> 1 から 100 までの数をプリントするプログラムを書け。
> ただし 3 の倍数のときは数の代わりに｢Fizz｣と、5 の倍数のときは｢Buzz｣とプリントし、3 と 5 両方の倍数の場合には｢FizzBuzz｣とプリントすること。

*テストおじさん*: これが

> [red]#1 から 1000# までの数をプリントするプログラムを書け。
> ただし 3 の倍数のときは数の代わりに｢Fizz｣と、5 の倍数のときは｢Buzz｣とプリントし、3 と 5 両方の倍数の場合には｢FizzBuzz｣とプリントすること。

*テストおじさん*: とか

> [red]#1 から 1000# までの数をプリントするプログラムを書け。
> ただし 3 の倍数のときは数の代わりに [red]#｢FizzFizzFizz｣# と、5 の倍数のときは [red]#｢BuzzBuzzBuzz｣# とプリントし、3 と 5 両方の倍数の場合には [red]#｢FizzBuzzFizzBuzzFizzBuzz｣# とプリントすること。
> [red]#ただし、上記の処理は月初のみに行うこと。#

*テストおじさん*: からの

> [red]#1 から 1000# までの数をプリントするプログラムを書け。
> ただし 3 の倍数のときは数の代わりに [red]#｢FizzFizzFizz｣# と、5 の倍数のときは [red]#｢BuzzBuzzBuzz｣# とプリントし、3 と 5 両方の倍数の場合には [red]#｢FizzBuzzFizzBuzzFizzBuzz｣# とプリントすること。
> [red]#ただし、上記の処理は月初のみに行うこと。#
> [red]#上記の仕様は現状のビジネスモデルの変更に伴い無効とする。#

*テスト鬼さん*: !

*テスト初めて書いたひと*: !!

*テストおじさん*: みたいに仕様が確定した後もコロコロ変わっていくと従来型の開発アプローチでは対応が難しいですよね。

*テストおじさん*: そういったビジネスとITの変化が [red]#アジャイルソフトウェア開発宣言# につながることになりました。

[quote, 'http://agilemanifesto.org/iso/ja/manifesto.html[アジャイルソフトウェア開発宣言]']
____

私たちは、ソフトウェア開発の実践

あるいは実践を手助けをする活動を通じて、

よりよい開発方法を見つけだそうとしている。

この活動を通して、私たちは以下の価値に至った。

プロセスやツールよりも個人と対話を、

包括的なドキュメントよりも動くソフトウェアを、

契約交渉よりも顧客との協調を、

計画に従うことよりも変化への対応を、

価値とする。すなわち、左記のことがらに価値があることを

認めながらも、私たちは右記のことがらにより価値をおく。
____

*テストおじさん*: そして [red]#アジャイル宣言の背後にある原則# を実現するための手法として [red]#XP（eXtreme Programming）# や [red]#スクラム# があります。

[quote, 'http://agilemanifesto.org/iso/ja/principles.html[アジャイル宣言の背後にある原則]']
____
私たちは以下の原則に従う:

顧客満足を最優先し、
価値のあるソフトウェアを早く継続的に提供します。

要求の変更はたとえ開発の後期であっても歓迎します。
変化を味方につけることによって、お客様の競争力を引き上げます。

動くソフトウェアを、2-3週間から2-3ヶ月という
できるだけ短い時間間隔でリリースします。

ビジネス側の人と開発者は、プロジェクトを通して
日々一緒に働かなければなりません。

意欲に満ちた人々を集めてプロジェクトを構成します。
環境と支援を与え仕事が無事終わるまで彼らを信頼します。

情報を伝えるもっとも効率的で効果的な方法は
フェイス・トゥ・フェイスで話をすることです。

動くソフトウェアこそが進捗の最も重要な尺度です。

アジャイル･プロセスは持続可能な開発を促進します。
一定のペースを継続的に維持できるようにしなければなりません。

技術的卓越性と優れた設計に対する
不断の注意が機敏さを高めます。

シンプルさ（ムダなく作れる量を最大限にすること）が本質です。

最良のアーキテクチャ・要求・設計は、
自己組織的なチームから生み出されます。

チームがもっと効率を高めることができるかを定期的に振り返り、
それに基づいて自分たちのやり方を最適に調整します。
____

*テストおじさん*: 要求をソフトウェアに落とし込むためのプラクティスとして [red]#ストーリー# や [red]#プロダクトバックログ# [red]#スプリントバックログ# なんてのがありますね。

*テストおじさん*: プログラムマ目線なら [red]#TODOリスト# は [red]#スプリントバックログ# より細かい粒度になるんじゃないかなと思ってます。

*テスト初めて書いたひと*: [red]#TODOリスト# に抜けや漏れがあった場合はどうするんですかね?

> 要求の変更はたとえ開発の後期であっても歓迎します。
> 変化を味方につけることによって、お客様の競争力を引き上げます。

*テストおじさん*: の原則に従い、[red]#テストファーストプログラミング# と [red]#インクリメンタルな設計# で [red]#TODOリスト# の抜けを埋めて漏れを塞ぎましょう。

=== テストファーストから始めるアーキテクチャ

==== テストファースト

*テストおじさん*: では1つ目の [red]#TODOリスト# から片付けていきましょうか。

ファイルを新規作成するテストおじさん。

*テストおじさん*: まずは [red]#テストファースト# で。

[source, bash]
----
 $ python main_test.py -v

 ----------------------------------------------------------------------
 Ran 0 tests in 0.000s

 OK
----

[quote, 'https://amzn.to/2QtCA5b[テスト駆動開発]']
____
テストファースト

いつテストを書くべきだろうか----それはテスト対象のコードを書く前だ。
____

==== アサートファースト

*テストおじさん*: さて、1から100までコンソールに出力させないといけませんがまずは [red]#アサートファースト# で [red]#仮実装# を行ってテストを通しておきましょう。

[quote, 'https://amzn.to/2QtCA5b[テスト駆動開発]']
____
アサートファースト

いつアサーションを書くべきだろうか----最初に書こう

* システム構築はどこから始めるべきだろうか。システム構築が終わったらこうなる、というストーリーを語るところからだ。
* 機能はどこから書き始めるべきだろうか。コードが書き終わったらこのように動く、というテストを書くところからだ。
* ではテストはどこから書き始めるべきだろうか。それはテストの終わりにパスすべきアサーションを書くところからだ。
____

[quote, 'https://amzn.to/2QtCA5b[テスト駆動開発]']
____
仮実装を経て本実装へ

失敗するテストを書いてから、最初に行う実装はどのようなものだろうか----ベタ書きの値を返そう。
____

*テストおじさん*: はい、オッケー。

[source, bash]
----
 $ python main_test.py -v
 test_1から100まで数をプリントできるようにする (__main__.MainTest) ... ok

 ----------------------------------------------------------------------
 Ran 1 test in 0.000s

 OK
----

*テスト鬼さん*: `-v` のオプションは？

*テストおじさん*: これは実施するテストを表示するオプションです。

*テストおじさん*: オプションなしで実行すると。

[source, bash]
----
 $ python main_test.py
 .
 ----------------------------------------------------------------------
 Ran 1 test in 0.000s

 OK
----

*テストおじさん*: こんな感じになります。

==== 仮実装

コードを書き換えてテストを実行するテストをおじさん。

[source, Python]
----
def execute():
    print(1)
----

[source, bash]
----
 python main_test.py
1
F
======================================================================
FAIL: test_1から100まで数をプリントできるようにする (__main__.MainTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "main_test.py", line 10, in test_1から100まで数をプリントできるようにする
    self.assertEqual("1", execute())
AssertionError: '1' != None

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
----

*テストおじさん*: 1をコンソールに出力はできたけど結果をどうやってアサーションしましょうかね。

*テストおじさん*: だいたいこんな時私は https://www.google.com/search?q=Python+unittest+%E6%A8%99%E6%BA%96%E5%87%BA%E5%8A%9B&ie=utf-8&oe=utf-8&client=firefox-b-ab[Python unittest 標準出力] みたいなキーワードでググります。

*テストおじさん*: いくつかの記事を眺めて良さげなのを試します。

*テストおじさん*: 今回は https://qiita.com/Asayu123/items/6f2471aa5ebe597b2638[こちらのQiitaの記事] を参考にさせていただきましょう。

いくつかコードを追記するテストおじさん

[source, Python]
----
import unittest
from test.support import captured_stdout


def execute():
    print(1)


class MainTest(unittest.TestCase):
    def test_1から100まで数をプリントできるようにする(self):
        with captured_stdout() as stdout:
            execute()
        self.assertEqual("1", stdout.getvalue())
----

*テストおじさん*: こうかな・・・テスト!

[source, bash]
----
$ python main_test.py -v
test_1から100まで数をプリントできるようにする (__main__.MainTest) ... FAIL

======================================================================
FAIL: test_1から100まで数をプリントできるようにする (__main__.MainTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "main_test.py", line 13, in test_1から100まで数をプリントできるようにする
    self.assertEqual("1", stdout.getvalue())
AssertionError: '1' != '1\n'
- 1
+ 1

?   +


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (failures=1)
----

*テストおじさん*: ありゃ、えーと `AssertionError: '1' != '1\n'` ・・・ふむ、改行されて出力されるのね。

[source, Python]
----
class MainTest(unittest.TestCase):
    def test_1から100まで数をプリントできるようにする(self):
        with captured_stdout() as stdout:
            execute()
        self.assertEqual("1\n", stdout.getvalue())
----

*テストおじさん*: これで・・・オッケー。

[source, bash]
----
 $ python main_test.py -v
test_1から100まで数をプリントできるようにする (__main__.MainTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
----

==== 三角測量

*テストおじさん*: さて、アサーションができようになったので [red]#while文# の制御構造を使って繰り返し実行の処理を実装してみましょう。

[source, Python]
----
def execute():
    n = 100
    while n != 0:
        print(n)
----

*テストおじさん*: はい、実行・・・おや？

[source, bash]
----
$ python main_test.py -v
test_1から100まで数をプリントできるようにする (__main__.MainTest) ...
----

*テストおじさん*: はい nがマイナスされないので `n != 0` の条件になることができず無限ループに入ってますね。

[source, Python]
----
def execute():
    n = 100
    while n != 0:
        print(n)
        n = n - 1
----

*テストおじさん*: これで、実行!

[source, bash]
----
$ python main_test.py -v
test_1から100まで数をプリントできるようにする (__main__.MainTest) ... FAIL

======================================================================
FAIL: test_1から100まで数をプリントできるようにする (__main__.MainTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "main_test.py", line 16, in test_1から100まで数をプリントできるようにする
    self.assertEqual("1\n", stdout.getvalue())
AssertionError: '1\n' != '100\n99\n98\n97\n96\n95\n94\n93\n92\n91\n9[346 chars]n1\n'
+ 100
+ 99
+ 98
+ 97
+ 96
+ 95
+ 94
+ 93
+ 92
+ 91
+ 90
+ 89
+ 88
+ 87
+ 86
+ 85
+ 84
+ 83
+ 82
+ 81
+ 80
+ 79
+ 78
+ 77
+ 76
+ 75
+ 74
+ 73
+ 72
+ 71
+ 70
+ 69
+ 68
+ 67
+ 66
+ 65
+ 64
+ 63
+ 62
+ 61
+ 60
+ 59
+ 58
+ 57
+ 56
+ 55
+ 54
+ 53
+ 52
+ 51
+ 50
+ 49
+ 48
+ 47
+ 46
+ 45
+ 44
+ 43
+ 42
+ 41
+ 40
+ 39
+ 38
+ 37
+ 36
+ 35
+ 34
+ 33
+ 32
+ 31
+ 30
+ 29
+ 28
+ 27
+ 26
+ 25
+ 24
+ 23
+ 22
+ 21
+ 20
+ 19
+ 18
+ 17
+ 16
+ 15
+ 14
+ 13
+ 12
+ 11
+ 10
+ 9
+ 8
+ 7
+ 6
+ 5
+ 4
+ 3
+ 2
  1


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
----

*テストおじさん*: 100まで出力できたけど今度はアサーションをどうしましょうかね。

*テストおじさん*: https://qiita.com/Asayu123/items/6f2471aa5ebe597b2638[先程参考にした記事] に実行結果を [red]#リスト(list)# に格納する方法が書いてあったので使わせていただきましょう。

[source, Python]
----
class MainTest(unittest.TestCase):
    def test_1から100まで数をプリントできるようにする(self):
        with captured_stdout() as stdout:
            execute()
            lines = stdout.getvalue().splitlines()

        self.assertEqual("1\n", lines[1])
----

*テストおじさん*: これでどうかな?

[source, bash]
----
$ python main_test.py -v
test_1から100まで数をプリントできるようにする (__main__.MainTest) ... FAIL

======================================================================
FAIL: test_1から100まで数をプリントできるようにする (__main__.MainTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "main_test.py", line 18, in test_1から100まで数をプリントできるようにする
    self.assertEqual("1\n", lines[1])
AssertionError: '1\n' != '99'
- 1
+ 99

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (failures=1)
----

*テストおじさん*: おや？ `AssertionError: '1\n' != '99'` ・・・改行コードはいらないのね・・・99?

デバッガを実行して `lines` を確認するテストおじさん。

*テストおじさん*: あーそうか、100から出力されてるからね。

[source, Python]
----
        self.assertEqual("1", lines[100])
----

*テストおじさん*: こうか！

[source, bash]
----
 $ python main_test.py -v
test_1から100まで数をプリントできるようにする (__main__.MainTest) ... ERROR

======================================================================
ERROR: test_1から100まで数をプリントできるようにする (__main__.MainTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "main_test.py", line 18, in test_1から100まで数をプリントできるようにする
    self.assertEqual("1", lines[100])
IndexError: list index out of range

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
----

*テストおじさん*: ファッ!? `IndexError: list index out of range` ・・・あー [red]#リスト(list)# は0から始まる仕様だったな。

*テストおじさん*: こうね。

[source, Python]
----
        self.assertEqual("1", lines[99])
----

*テストおじさん*: オッケー!

[source, bash]
----
$ python main_test.py -v
test_1から100まで数をプリントできるようにする (__main__.MainTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
----

*テストおじさん*: [red]#三角測量# を実施して100が出力していることも確認しておきましょう。

[quote, 'https://amzn.to/2QtCA5b[テスト駆動開発]']
____
三角測量

テストから最も慎重に一般化を引き出すやり方はどのようなものだろうか----２つ以上の例があるときだけ、一般化を行うようにしよう。
____

*テストおじさん*: 一番最初のリストの添字は0だから・・・

[source, Python]
----
    def test_1から100まで数をプリントできるようにする(self):
        with captured_stdout() as stdout:
            execute()
            lines = stdout.getvalue().splitlines()

        self.assertEqual("1", lines[99])
        self.assertEqual("100", lines[0])
----

*テストおじさん*: はい、オッケー!

[source, bash]
----
$ python main_test.py -v
test_1から100まで数をプリントできるようにする (__main__.MainTest) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
----

*テストおじさん*: [red]#TODOリスト# 一つ目を片付けることができました。

* [x] 1 から 100 まで数をプリントできるようにする。
* [ ] 3 の倍数のときは数の代わりに｢Fizz｣をプリントできるようにする。
* [ ] 5 の倍数のときは｢Buzz｣とプリントできるようにする。
* [ ] 3 と 5 両方の倍数の場合には｢FizzBuzz｣とプリントできるようにする。

==== 明白な実装

*テストおじさん*: さて、　二つ目の [red]#TODOリスト# に取り掛かるとしましょうか。

テストコードを追加するテストおじさん。

[source, Python]
----
    def test_3の倍数のときは数の代わりにFizzをプリントする(self):
        with captured_stdout() as stdout:
            execute()
            lines = stdout.getvalue().splitlines()
        self.assertEqual("Fizz", lines[97])
----

*テストおじさん*: テストは・・・失敗するね、オッケー。

[source, bash]
----
$ python main_test.py -v
test_1から100まで数をプリントできるようにする (__main__.MainTest) ... ok
test_3の倍数のときは数の代わりにFizzをプリントする (__main__.MainTest) ... FAIL

======================================================================
FAIL: test_3の倍数のときは数の代わりにFizzをプリントする (__main__.MainTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "main_test.py", line 25, in test_3の倍数のときは数の代わりにFizzをプリントする
    self.assertEqual("Fizz", lines[97])
AssertionError: 'Fizz' != '3'
- Fizz
+ 3


----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=1)
----

*テスト初めて書いたひと*: テストが失敗するのにオッケーだと!?

ニヤリと笑うテストおじさん。

*テストおじさん*: お忘れなく・・・今やっていることはテストではなく設計だということ。

[quote, 'https://amzn.to/2QtCA5b[テスト駆動開発]']
____
皮肉なことに、TDDはテスト技法ではない（Cunninghamの公案)。TDDは分析技法であり、設計技法であり、実際には開発のすべてのアクティビティを構造化する技法なのだ。
____

*テストおじさん*: さて、では設計を満たす振る舞いを [red]#明白な実装# しましょう。

[source, Python]
----
def execute():
    n = 100
    while n != 0:
        if n % 3 == 0:
            print("Fizz")
        print(n)
        n = n - 1
----

*テストおじさん*: えい!

[source, bash]
----
 $ python main_test.py -v
test_1から100まで数をプリントできるようにする (__main__.MainTest) ... FAIL
test_3の倍数のときは数の代わりにFizzをプリントする (__main__.MainTest) ... ok

======================================================================
FAIL: test_1から100まで数をプリントできるようにする (__main__.MainTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "main_test.py", line 20, in test_1から100まで数をプリントできるようにする
    self.assertEqual("1", lines[99])
AssertionError: '1' != '26'
- 1
+ 26


----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (failures=1)
----

*テストおじさん*: おや、最初のテストが失敗してしまいました。

変更箇所を眺めるテストおじさん。

[source, Python]
----
def execute():
    n = 100
    while n != 0:
        if n % 3 == 0:
            print("Fizz") <1>
        print(n) <2>
        n = n - 1
----

*テストおじさん*: あー、printが２回実行されてますね。

*テストおじさん*: ここはこうで・・・

[source, Python]
----
def execute():
    n = 100
    while n != 0:
        if n % 3 == 0:
            print("Fizz")
        else:
            print(n)
        n = n - 1
----

*テストおじさん*: こう！

[source, bash]
----
$ python main_test.py -v
test_1から100まで数をプリントできるようにする (__main__.MainTest) ... ok
test_3の倍数のときは数の代わりにFizzをプリントする (__main__.MainTest) ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.001s

OK
----

*テストおじさん*: [red]#TODOリスト# 二つ目を片付けることができました。

* [x] 1 から 100 まで数をプリントできるようにする。
* [x] 3 の倍数のときは数の代わりに｢Fizz｣をプリントできるようにする。
* [ ] 5 の倍数のときは｢Buzz｣とプリントできるようにする。
* [ ] 3 と 5 両方の倍数の場合には｢FizzBuzz｣とプリントできるようにする。



=== リファクタリングから始める構造化プログラミング

== ふりかえり
[source, Markdown]
----
include::../../../dev/20181116/replay/README.md[]
----

[source, Python]
----
include::../../../dev/20181116/replay/main_test.py[]
----


==== Keep

==== Problem

==== Try

== 参照

=== 参考図書

++++
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="https://rcm-fe.amazon-adsystem.com/e/cm?ref=qf_sp_asin_til&t=k2works0c-22&m=amazon&o=9&p=8&l=as1&IS1=1&detail=1&asins=4274217884&linkId=568f25b974af5645e862928a12c354e1&bc1=ffffff&lt1=_top&fc1=333333&lc1=0066c0&bg1=ffffff&f=ifr"></iframe>
++++

=== 参考リンク

* https://www.buildinsider.net/enterprise/agile/01[アジャイルとは何か？ ツールと開発手法「スクラム／XP」、ウォーターフォールとの違い]
