:toc: left
:toclevels: 5
:sectnums:

= 見知らぬ、構造化プログラミング

== 概要
=== 実施日時
* https://hiroshima-arc.connpass.com/event/109589/[2018年11月16日（金） 18:00 - 21:00]

=== 会場

++++
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d6584.583947396631!2d132.458662!3d34.393924!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xe874ed70577dcf46!2z44Kz44Ov44O844Kt44Oz44Kw44K544Oa44O844K5IFNoYWtlSGFuZHM!5e0!3m2!1sja!2sjp!4v1541923570346" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
++++

=== 参加メンバー
* https://portfolio.forkwell.com/@k2works[テストおじさん]
* リモートさん
* テスト鬼さん
* テスト初めて書いたひと

=== お題
* http://www.hiroshima-arc.org/re_zero_tdd/fizz_buzz.html[FizzBuzz]
* FizzBuzz をクラスを使わずにテスト駆動で実装する。

=== 言語
* Python 3.6

== セッション

=== 前回までのあらすじ

http://www.hiroshima-arc.org/re_zero_tdd/session/20181109.html#_problem[前回のセッション]でクラスベースだとオブジェクト指向に関する解説も必要になることがわかったテストおじさん。

そこで今回はクラスを使わずにテスト駆動開発をやってみることにしたのであった。

さてさてどうなることやら・・・

=== TODOリストから始めるプロジェクト管理

==== 仕様

*テストおじさん*: はい、第２回 Re:ゼロから始めるテスト駆動開発 はじめます、レポジトリは https://github.com/hiroshima-arc/re_zero_tdd[ここ]ね。

*リモートさん*: 今日は家からうっすら参加です。ご飯を食べたりで適当に抜けています。

*テスト鬼さん*: よろしくお願いします。

*テスト初めて書いたひと*: よろしくお願いします。

*テストおじさん*: 今日はFizzBuzzをクラスを使わずにテスト駆動で実装してみたいと思います。

*テストおじさん*: 今回のお題の仕様です。

> 1 から 100 までの数をプリントするプログラムを書け。
> ただし 3 の倍数のときは数の代わりに｢Fizz｣と、5 の倍数のときは｢Buzz｣とプリントし、3 と 5 両方の倍数の場合には｢FizzBuzz｣とプリントすること。

*テストおじさん*: http://www.hiroshima-arc.org/re_zero_tdd/session/20181109.html#_%E3%82%BB%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3[前回のセッション]との違いとして今回はコンソールに出力させるというのが大きな違いですかね。

==== TODOリスト

*テストおじさん*: 最初にまず [red]#TODOリスト# の作成をしましょう。

[quote, 'https://amzn.to/2QtCA5b[テスト駆動開発]']
____
TODOリスト

何をテストすべきだろうか----着手する前に、必要になりそうなテストをリストに書き出しておこう。
____

*テストおじさん*: 仕様からTODOリストを作成するわけですがここは [red]#一つのプログラムには一つのことをうまくやらせる# の原則に従ってシンプルにやってみましょう。

TODOリストを書き出すテストおじさん。

* [ ] 1 から 100 まで数をプリントできるようにする。
* [ ] 3 の倍数のときは数の代わりに｢Fizz｣をプリントできるようにする。
* [ ] 5 の倍数のときは｢Buzz｣とプリントできるようにする。
* [ ] 3 と 5 両方の倍数の場合には｢FizzBuzz｣とプリントできるようにする。

*テストおじさん*: まずは100回繰り返し処理をすることをどうやって実装するかを考えるとして条件に関しては一旦置いておきましょう。

*テストおじさん*: 一つのTODOには一つのことをテストできるようにする・・・みたいな。




=== テストファーストから始めるアーキテクチャ

=== リファクタリングから始める構造化プログラミング

== ふりかえり
[source, Markdown]
----
include::../../../dev/20181116/replay/README.md[]
----

==== Keep

==== Problem

==== Try

== 参照

=== 参考図書

++++
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="https://rcm-fe.amazon-adsystem.com/e/cm?ref=qf_sp_asin_til&t=k2works0c-22&m=amazon&o=9&p=8&l=as1&IS1=1&detail=1&asins=4274217884&linkId=568f25b974af5645e862928a12c354e1&bc1=ffffff&lt1=_top&fc1=333333&lc1=0066c0&bg1=ffffff&f=ifr"></iframe>
++++

=== 参考リンク
