:toc: left
:toclevels: 5
:sectnums:

= 見知らぬ、構造化プログラミング

== 概要
=== 実施日時
* https://hiroshima-arc.connpass.com/event/109589/[2018年11月16日（金） 18:00 - 21:00]

=== 会場

++++
<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d6584.583947396631!2d132.458662!3d34.393924!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xe874ed70577dcf46!2z44Kz44Ov44O844Kt44Oz44Kw44K544Oa44O844K5IFNoYWtlSGFuZHM!5e0!3m2!1sja!2sjp!4v1541923570346" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
++++

=== 参加メンバー
* https://portfolio.forkwell.com/@k2works[テストおじさん]
* リモートさん
* テスト鬼さん
* テスト初めて書いたひと

=== お題
* http://www.hiroshima-arc.org/re_zero_tdd/fizz_buzz.html[FizzBuzz]
* FizzBuzz をクラスを使わずにテスト駆動で実装する。

=== 言語
* Python 3.6

== セッション

=== 前回までのあらすじ

http://www.hiroshima-arc.org/re_zero_tdd/session/20181109.html#_problem[前回のセッション]でクラスベースだとオブジェクト指向に関する解説も必要になることがわかったテストおじさん。

そこで今回はクラスを使わずにテスト駆動開発をやってみることにしたのであった。

さてさてどうなることやら・・・

=== TODOリストから始めるアジャイルソフトウェア開発

==== 仕様

*テストおじさん*: はい、第２回 Re:ゼロから始めるテスト駆動開発 はじめます、レポジトリは https://github.com/hiroshima-arc/re_zero_tdd[ここ]ね。

*リモートさん*: 今日は家からうっすら参加です。ご飯を食べたりで適当に抜けています。

*テスト鬼さん*: よろしくお願いします。

*テスト初めて書いたひと*: よろしくお願いします。

*テストおじさん*: 今日はFizzBuzzをクラスを使わずにテスト駆動で実装してみたいと思います。

*テストおじさん*: 今回のお題の仕様です。

> 1 から 100 までの数をプリントするプログラムを書け。
> ただし 3 の倍数のときは数の代わりに｢Fizz｣と、5 の倍数のときは｢Buzz｣とプリントし、3 と 5 両方の倍数の場合には｢FizzBuzz｣とプリントすること。

*テストおじさん*: http://www.hiroshima-arc.org/re_zero_tdd/session/20181109.html#_%E3%82%BB%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3[前回のセッション]との違いとして今回はコンソールに出力させるというのが大きな違いですかね。

==== TODOリスト

*テストおじさん*: 最初にまず [red]#TODOリスト# の作成をしましょう。

[quote, 'https://amzn.to/2QtCA5b[テスト駆動開発]']
____
TODOリスト

何をテストすべきだろうか----着手する前に、必要になりそうなテストをリストに書き出しておこう。
____

*テストおじさん*: 仕様からTODOリストを作成するわけですがここは [red]#一つのプログラムには一つのことをうまくやらせる# の原則に従ってシンプルにやってみましょう。

TODOリストを書き出すテストおじさん。

* [ ] 1 から 100 まで数をプリントできるようにする。
* [ ] 3 の倍数のときは数の代わりに｢Fizz｣をプリントできるようにする。
* [ ] 5 の倍数のときは｢Buzz｣とプリントできるようにする。
* [ ] 3 と 5 両方の倍数の場合には｢FizzBuzz｣とプリントできるようにする。

*テストおじさん*: まずは100回繰り返し処理をすることをどうやって実装するかを考えるとして条件に関しては一旦置いておきましょう。

*テストおじさん*: 一つのTODOには一つのことをテストできるようにする・・・みたいな。

==== アジャイルソフトウェア開発

*テスト鬼さん*: TODOリストの粒度はどれくらいが適切なんですかね？

*テストおじさん*: 自分はテストメソッドに対応するぐらいを目安に書いてますね。

*テスト初めて書いたひと*: 実際の開発だとTODOリストの粒度って立場によって変わってくると思うんですがどう取りまとめて行けばいいんですかね？

*テストおじさん*: そうですよね、作業者レベルのTODOもアプリケーションの要求から落とし込まないといけませよね。

*テストおじさん*: そういったものをどう取り扱うかは [red]#アジャイルソフトウェア開発手法# が参考になるかと思います。

*テスト初めて書いたひと*: アジャイル?

*テストおじさん*: えーとです、例えば今日のお題の仕様ですが。

> 1 から 100 までの数をプリントするプログラムを書け。
> ただし 3 の倍数のときは数の代わりに｢Fizz｣と、5 の倍数のときは｢Buzz｣とプリントし、3 と 5 両方の倍数の場合には｢FizzBuzz｣とプリントすること。

*テストおじさん*: これが

> [red]#1 から 1000# までの数をプリントするプログラムを書け。
> ただし 3 の倍数のときは数の代わりに｢Fizz｣と、5 の倍数のときは｢Buzz｣とプリントし、3 と 5 両方の倍数の場合には｢FizzBuzz｣とプリントすること。

*テストおじさん*: とか

> [red]#1 から 1000# までの数をプリントするプログラムを書け。
> ただし 3 の倍数のときは数の代わりに [red]#｢FizzFizzFizz｣# と、5 の倍数のときは [red]#｢BuzzBuzzBuzz｣# とプリントし、3 と 5 両方の倍数の場合には [red]#｢FizzBuzzFizzBuzzFizzBuzz｣# とプリントすること。
> [red]#ただし、上記の処理は月初のみに行うこと。#

*テストおじさん*: からの

> [red]#1 から 1000# までの数をプリントするプログラムを書け。
> ただし 3 の倍数のときは数の代わりに [red]#｢FizzFizzFizz｣# と、5 の倍数のときは [red]#｢BuzzBuzzBuzz｣# とプリントし、3 と 5 両方の倍数の場合には [red]#｢FizzBuzzFizzBuzzFizzBuzz｣# とプリントすること。
> [red]#ただし、上記の処理は月初のみに行うこと。#
> [red]#上記の仕様は現状のビジネスモデルの変更に伴い無効とする。#

*テスト鬼さん*: !

*テスト初めて書いたひと*: !!

*テストおじさん*: みたいに仕様が確定した後もコロコロ変わっていくと従来型の開発アプローチでは対応が難しいですよね。

*テストおじさん*: そういったビジネスとITの変化が [red]#アジャイルソフトウェア開発宣言# につながることになりました。

[quote, 'http://agilemanifesto.org/iso/ja/manifesto.html[アジャイルソフトウェア開発宣言]']
____

私たちは、ソフトウェア開発の実践

あるいは実践を手助けをする活動を通じて、

よりよい開発方法を見つけだそうとしている。

この活動を通して、私たちは以下の価値に至った。

プロセスやツールよりも個人と対話を、

包括的なドキュメントよりも動くソフトウェアを、

契約交渉よりも顧客との協調を、

計画に従うことよりも変化への対応を、

価値とする。すなわち、左記のことがらに価値があることを

認めながらも、私たちは右記のことがらにより価値をおく。
____

*テストおじさん*: そして [red]#アジャイル宣言の背後にある原則# を実現するための手法として [red]#XP（eXtreme Programming）# や [red]#スクラム# があります。

[quote, 'http://agilemanifesto.org/iso/ja/principles.html[アジャイル宣言の背後にある原則]']
____
私たちは以下の原則に従う:

顧客満足を最優先し、
価値のあるソフトウェアを早く継続的に提供します。

要求の変更はたとえ開発の後期であっても歓迎します。
変化を味方につけることによって、お客様の競争力を引き上げます。

動くソフトウェアを、2-3週間から2-3ヶ月という
できるだけ短い時間間隔でリリースします。

ビジネス側の人と開発者は、プロジェクトを通して
日々一緒に働かなければなりません。

意欲に満ちた人々を集めてプロジェクトを構成します。
環境と支援を与え仕事が無事終わるまで彼らを信頼します。

情報を伝えるもっとも効率的で効果的な方法は
フェイス・トゥ・フェイスで話をすることです。

動くソフトウェアこそが進捗の最も重要な尺度です。

アジャイル･プロセスは持続可能な開発を促進します。
一定のペースを継続的に維持できるようにしなければなりません。

技術的卓越性と優れた設計に対する
不断の注意が機敏さを高めます。

シンプルさ（ムダなく作れる量を最大限にすること）が本質です。

最良のアーキテクチャ・要求・設計は、
自己組織的なチームから生み出されます。

チームがもっと効率を高めることができるかを定期的に振り返り、
それに基づいて自分たちのやり方を最適に調整します。
____

*テストおじさん*: 要求をソフトウェアに落とし込むためのプラクティスとして [red]#ストーリー# や [red]#プロダクトバックログ# [red]#スプリントバックログ# なんてのがありますね。

*テストおじさん*: プログラムマ目線なら [red]#TODOリスト# は [red]#スプリントバックログ# より細かい粒度になるんじゃないかなと思ってます。

*テスト初めて書いたひと*: [red]#TODOリスト# に抜けや漏れがあった場合はどうするんですかね?

> 要求の変更はたとえ開発の後期であっても歓迎します。
> 変化を味方につけることによって、お客様の競争力を引き上げます。

*テストおじさん*: の原則に従い、[red]#テストファーストプログラミング# と [red]#インクリメンタルな設計# で [red]#TODOリスト# の抜けを埋めて漏れを塞ぎましょう。




=== テストファーストから始めるアーキテクチャ

=== リファクタリングから始める構造化プログラミング

== ふりかえり
[source, Markdown]
----
include::../../../dev/20181116/replay/README.md[]
----

==== Keep

==== Problem

==== Try

== 参照

=== 参考図書

++++
<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="https://rcm-fe.amazon-adsystem.com/e/cm?ref=qf_sp_asin_til&t=k2works0c-22&m=amazon&o=9&p=8&l=as1&IS1=1&detail=1&asins=4274217884&linkId=568f25b974af5645e862928a12c354e1&bc1=ffffff&lt1=_top&fc1=333333&lc1=0066c0&bg1=ffffff&f=ifr"></iframe>
++++

=== 参考リンク

* https://www.buildinsider.net/enterprise/agile/01[アジャイルとは何か？ ツールと開発手法「スクラム／XP」、ウォーターフォールとの違い]
