version: '3'
services:
  app:
    image: app
    build:
      context: app/ContosoUniversity
    ports:
      - "8000:80"
  dev:
    image: dev
    working_dir: /app
    build: .
    volumes:
      - ./:/app
