version: '3'
services:
  app:
    image: app
    build:
      context: app/ContosoUniversity
    ports:
      - "8000:80"
  db:
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=P@ssw0rd!
    ports:
      - "1433:1433"
  dev:
    image: dev
    working_dir: /app
    build: .
    volumes:
      - ./:/app
